name: Sync Manual (Public)

on:
  push:
    branches: [ main ]

jobs:
  force-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Eksekusi Push Manual
        env:
          # Pastikan SECRET ini sudah ada di Settings > Secrets > Actions
          TOKEN_SAYA: ${{ secrets.API_TOKEN_GITHUB }} 
        run: |
          # 1. Setting Identitas
          git config --global user.email "eventhmpbisdigupy@gmail.com"
          git config --global user.name "Auto Sync Bot"
          
          # 2. Masukkan Remote URL dengan TOKEN di dalamnya
          # Ini kuncinya: Token diselipkan di depan @github.com
          git remote add repo_sebelah https://Hunion-dev:$TOKEN_SAYA@github.com/Hunion-dev/event_kuyu.git
          
          # 3. Download dulu data dari sana (Fetch)
          git fetch repo_sebelah
          
          # 4. Timpa (Force Push) data di sana dengan data dari sini
          git push -f repo_sebelah main
