name: Sync ke Repo Lain

on:
  push:
    branches: [ main ] # Pastikan ini sesuai branch utama Anda (bisa 'main' atau 'master')

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push ke Repository Tujuan
        uses: cpina/github-action-push-to-another-repository@main
        env:
          # Ini mengambil kunci yang sudah Anda simpan di Bagian 2A tadi
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '.'
          destination-github-username: 'Hunion-dev'      # Username Akun KEDUA
          destination-repository-name: 'event_kuyu'       # Nama Repo di Akun KEDUA (JANGAN pakai tanda / )
          user-email: 'eventhmpbisdigupy@gmail.com'      # Email yang akan tampil di history commit
          target-branch: main                            # Branch di repo Akun KEDUA
